# JWT Configuration
jwt:
  secret: your-secret-key
  expiration: 86400000 # Token expiration time in milliseconds (e.g., 24 hours)
  header: Authorization
  prefix: Bearer

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: x88p99qxzmdvgmdu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8088
